language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: an0o0nym
  password:
    secure: utlWaqrcZ741+vxOus+PYgpLgNQG3hhLysQI1WblXqDUaPHs2fmbBEZBpL+35NsfdEfaJUysI6Sn1ru9/eowKkhjSXuU8Cu4hBI9FqZamHt7+RUZkCm9bqeGsI5ukGqkJU0wZgdHoEzN91k8HopYit6H9YN9gqd02uVDFY/kGjW/Js3TVRgZT5fSTxwvHBiYBaPvUrDryuX02EPOod2wf7Lz6aKov5ITqo+noPAy9caJOrTee14LWdJPOK1+/c29/okkabyMyUfFyRXbAT1sZYCO3o42qhdapzzMuUVmvR2ve5r0thnbuEmG/sfPKRcMS2iA3uoxoLrxMfTAFIAsYNnRFhzyXnLZTYltSanRYoF4CglebowJiuzD7izh9kACu1832TCJ5O0+uED9BTQVU85GeWE0OZTmnxjqzh4b6z2++lojISQ8NqXMgE73zTgu4YqzbGQxvRVtiwCz9c9edzVKA0+MkMEgKUJdOxHbkqWmeyP6407VQx6xmOPeNYe1LL4TrjgpMNIjg2ndaVLL1968GfCEdh8YuUUIQqANL8nNUUh69qrC5jNIx40/Q4aOveuhUDj62MAPxRDeXglLpDUlFs/foKWlPEq6h2WtJWMUnDF1KI9L+/WI9P0dMCSL6+RIhzJ345cJ/+Z6Z2mYWt7VW4VFNcdc802AOhuXFJM=
  on:
    tags: true
    repo: an0o0nym/website_monitor
    python: 3.5
